name: Go build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-go-lib:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-lib.yaml@feat/do-not-duplicate-build-runs
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
